---

# where smr will be installed
smr_home_dir: /root/dockerize

smr_mysql_host: smr-mysql
smr_mysql_root_password: "{{ vault_smr_mysql_root_password }}"

smr_recaptcha_public: 6Lc4l8ISAAAAALJfhbyDcLI0wOt9ZEhIfeG9Bdk0
smr_recaptcha_private: "{{ vault_smr_recaptcha_private }}"

smr_facebook_app_id: 135977559774648
smr_facebook_app_secret: "{{ vault_smr_facebook_app_secret }}"

smr_google_analytics_id: UA-141756852-1

smr_s3_access_key: "{{ vault_smr_s3_access_key }}"
smr_s3_secret_key: "{{ vault_smr_s3_secret_key }}"

smr_discord_token: "{{ vault_smr_discord_token }}"

smr_irc_bot_pass: "{{ vault_smr_irc_bot_pass }}"
